### ISSUE TITLE
Lambda@Edge construct

### ISSUE THREAD

**Issue by xhci** [tmokmss/cdk-lambda-llrt#3]
It's unclear to me if LLRT is able to run on Lambda@Edge yet, but a construct would be nice if/when available.

**Comment by tmokmss** [comment]
Hi @xhci, I guess we cannot use LLRT at the moment. because Lambda@Edge does not currently support `provided.al2023` runtime ([doc](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-at-edge-function-restrictions.html#lambda-at-edge-restrictions-runtime)), which is required to use [a custom runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html) such as LLRT.

**Comment by xhci** [comment]
Hi @tmokmss - thanks for looking into this! I'll close the issue for now, but hopefully it's supported by AWS in the future.

**Comment by tmokmss** [comment]
I wondrered if we could use [the wrapper script feature](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-modify.html#runtime-wrapper) to use LLRT on Node.js managed runtime, but it was also impossible because Lambda@Edge [does not support](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-at-edge-function-restrictions.html#lambda-at-edge-restrictions-features) environment variables.
